version: '3'
services:
  node:
    build:
      context: ./server
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "13000:5000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - ENABLE_LOAD_TEST_ENDPOINT=${ENABLE_LOAD_TEST_ENDPOINT:-false}
    depends_on:
      - postgres
      - ml-service
    restart: always
  frontend:
    build:
      context: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - node
    restart: always
  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: Stylify123!
      POSTGRES_USER: leoniddas7
      POSTGRES_DB: postgres

  ml-service:
    build:
      context: ./ml-service
    ports:
      - "8000:8000"
    volumes:
      - ./ml-service:/app
      - ml_models_cache:/root/.cache/huggingface
    restart: always

volumes:
  postgres_data:
  ml_models_cache:
